### ISSUE TITLE
[Game] result page

### ISSUE THREAD

**Issue by gtd9511** [transcendence-42seoul/transcendence_front#15]
## 📃 Description
game result page 제작

## ☑ Todo
- [x] game db 생성 후 연결하기
- [x] ready 페이지와 마찬가지로 시간이 지나면 창 넘어가기
- [x] 추가로 나가기 버튼
- [x] 기본적인 구현 이후는 game db 스코어와 연결하기
