### ISSUE TITLE
[Chat] 패스워드 수정에 관한 새로운 기능..

### ISSUE THREAD

**Issue by www-castlehi-com** [transcendence-42seoul/transcendence_front#40]
## 📃 Description
왜 새로운게 계속 생기지

## ☑ Todo
- [x] 방 생성 후 방장이 패스워드 생성 (public -> private)
- [x] 방 생성 후 방장이 패스워드 수정 
- [x] 방 생성 후 방장이 패스워드 제거 (private -> public)
