### ISSUE TITLE
[Client] 닉네임 변경

### ISSUE THREAD

**Issue by www-castlehi-com** [transcendence-42seoul/transcendence_front#43]
## 📃 Description
초기 회원가입, 마이페이지에서 닉네임도 변경 가능해야함
고유 닉네임 확인

## ☑ Todo
- [x] 초기 회원가입에서 고유 닉네임 설정
- [x] 아바타 설정 백엔드 연결
- [x] 마이페이지에서 닉네임 변경
