### ISSUE TITLE
게임 Refactor,Style 

### ISSUE THREAD

**Issue by seokunee** [transcendence-42seoul/transcendence_front#44]
## 📃 Description

- GamePage 리펙토링 및 디자인 수정

## ☑ Todo
- [x] 미니채팅 height 오류
- [x] 주석 및 안쓰는 코드 제거
- [x] 게임 페이지(플레이, 레디) 디자인 변경
- [x] 레이아웃 안맡는거 수정(ready 프로필 글자 벗어나는 거)
