### ISSUE TITLE
[Client] 메인, 채팅 페이지 Rest API

### ISSUE THREAD

**Issue by www-castlehi-com** [transcendence-42seoul/transcendence_front#48]
## 📃 Description
- 프론트에 db 정보 넣기

## ☑ Todo
- [x] 메인페이지 프로필 연결
- [x] 메인페이지 친구 목록 연결
- [x] 채팅페이지 프로필 연결
- [x] 채팅페이지 채팅 참여 목록 연결
- [x] 채팅페이지 친구 목록 연결
