### ISSUE TITLE
[Game/Feat] 친구목록과 채팅 목록에서 챌린지 신청 기능 완성하기

### ISSUE THREAD

**Issue by seokunee** [transcendence-42seoul/transcendence_front#54]
## 📃 Description
설명을 작성하세요.

## ☑ Todo
- [x] 친구 목록 챌린지 신청
- [x] 채팅 목록 챌린지 신청
- [x] 메인 페이지 로비 목록 챌린지 신청
- [x] 노말, 하드 적용
- [x] 신청한 사람이 취소한 경우, 양쪽 다 창 없애기
- [x] 신청할때 모두, user idx 두개 정보 저장 방식 고려하기
- [x] 챌린지 신청 알림에 normal, hard 표시
- [x] 알림 타임 리밋 => 5초 지나면 자동 취소

**Comment by gtd9511** [comment]
231203 02:16 친구목록에서 챌린지 기능 아직 반응 X
