### ISSUE TITLE
welcome & set page

### ISSUE THREAD

**Issue by jungeun919** [transcendence-42seoul/transcendence_front#65]
## 📃 Description
웰컴 디자인 수정

## ☑ Todo
- [x] 웰컴 디자인 수정 -> 컨펌 받기
- [x] 수정한 디자인대로 설정하기
- [x] 첫 로그인 때, 닉네임 미입력한 상태로 종료한 경우 계속 입력 창 띄워주기
