### ISSUE TITLE
[Client] owner는 admin 권한을 줬다 뺏어

### ISSUE THREAD

**Issue by www-castlehi-com** [transcendence-42seoul/transcendence_front#67]
## 📃 Description
채팅 권한 설정

## ☑ Todo
- [x] owner이 admin 권한 주기
- [x] owner가 admin 권한 뺏기

**Comment by jungeun919** [comment]
- [x] 본인이 본인 우클릭 막기
