### ISSUE TITLE
전체적인 수정

### ISSUE THREAD

**Issue by seokunee** [transcendence-42seoul/transcendence_front#76]
## ☑ Todo
- [x] 테스트 로그인 화면 적용
- [x] 닉네임 미입력 설정 시, 메인 페이지 이동 불가 처리
- [x] 챌린지 신청 실패 시 문구 수정
- [x] 챌린지 도전 왔을 때 모달 메시지 수정
