### ISSUE TITLE
[Game] Match History 

### ISSUE THREAD

**Issue by seokunee** [transcendence-42seoul/transcendence_front#78]
## 📃 Description

- 게임 매칭 기록

## ☑ Todo
- [x] 게임 매칭 기록 저장하기
- [x] 유저 프로필에 게임 히스토리 표시하기
- [x] MyPage 리펙토링
- [x] MyPage, UserPage 통합하기
- [x] 온라인 목록에서 챌린지 하면 알람 에러나는거 수정
